spring:
  application:
    name: finance-service

server:
  port: 8020


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/
  instance:
    hostname: localhost